/*
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 *
 * Copyright (c) 2019. Bo Zun (Tianjin) Education Technology Co., Ltd. and/or its affiliates. All rights reserved.
 * Bo Zun (Tianjin) Education Technology Co., Ltd. PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */

//LAYOUT
export const SIDEBAR_STATUS_START = 'SIDEBAR_STATUS_START';
export const SIDEBAR_STATUS_UPDATE = 'SIDEBAR_STATUS_UPDATE';
export const SIDEBAR_VIEW_START = 'SIDEBAR_VIEW_START';
export const SIDEBAR_VIEW_UPDATE = 'SIDEBAR_VIEW_UPDATE';
export const TOAST_UPDATE = 'TOAST_UPDATE';

//SIGNIN
export const SIGN_IN_START = 'SIGN_IN_START';
export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';

//SIGNUP
export const SIGN_UP_START = 'SIGN_UP_START';
export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';

//SET AUTHORIZATION
export const AUTH_USER = 'AUTH_USER';

//FACEBOOK
export const FACEBOOK_LOGIN_START = 'FACEBOOK_LOGIN_START';
export const FACEBOOK_LOGIN_REQUEST = 'FACEBOOK_LOGIN_REQUEST';
export const FACEBOOK_LOGIN_SUCCESS = 'FACEBOOK_LOGIN_SUCCESS';
export const FACEBOOK_LOGIN_FAILURE = 'FACEBOOK_LOGIN_FAILURE';

//LINKEDIN
export const LINKEDIN_LOGIN_START = 'LINKEDIN_LOGIN_START';
export const LINKEDIN_LOGIN_REQUEST = 'LINKEDIN_LOGIN_REQUEST';
export const LINKEDIN_LOGIN_SUCCESS = 'LINKEDIN_LOGIN_SUCCESS';
export const LINKEDIN_LOGIN_FAILURE = 'LINKEDIN_LOGIN_FAILURE';

//GET USER
export const GET_USER_START = 'GET_USER_START';
export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILURE = 'GET_USER_FAILURE';

//UPDATE USER
export const UPDATE_USER_START = 'UPDATE_USER_START';
export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';

//GET PROFILE
export const GET_PROFILE_START = 'GET_PROFILE_START';
export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAILURE = 'GET_PROFILE_FAILURE';

//CREATE PROFILE
export const CREATE_PROFILE_START = 'CREATE_PROFILE_START';
export const CREATE_PROFILE_REQUEST = 'CREATE_PROFILE_REQUEST';
export const CREATE_PROFILE_SUCCESS = 'CREATE_PROFILE_SUCCESS';
export const CREATE_PROFILE_FAILURE = 'CREATE_PROFILE_FAILURE';

//UPDATE PROFILE
export const UPDATE_PROFILE_START = 'UPDATE_PROFILE_START';
export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE';

//CREATE JOB
export const CREATE_JOB_START = 'CREATE_JOB_START';
export const CREATE_JOB_REQUEST = 'CREATE_JOB_REQUEST';
export const CREATE_JOB_SUCCESS = 'CREATE_JOB_SUCCESS';
export const CREATE_JOB_FAILURE = 'CREATE_JOB_FAILURE';

//GET JOB
export const GET_JOB_START = 'GET_JOB_START';
export const GET_JOB_REQUEST = 'GET_JOB_REQUEST';
export const GET_JOB_SUCCESS = 'GET_JOB_SUCCESS';
export const GET_JOB_FAILURE = 'GET_JOB_FAILURE';

//GET IP
export const GET_IP_ADDRESS_START = 'GET_IP_ADDRESS_START';
export const GET_IP_ADDRESS_REQUEST = 'GET_IP_ADDRESS_REQUEST';
export const GET_IP_ADDRESS_SUCCESS = 'GET_IP_ADDRESS_SUCCESS';
export const GET_IP_ADDRESS_FAILURE = 'GET_IP_ADDRESS_FAILURE';

//UPLOAD IMAGE
export const UPLOAD_IMAGE_START = 'UPLOAD_IMAGE_START';
export const UPLOAD_IMAGE_MOBILE_START = 'UPLOAD_IMAGE_MOBILE_START';//FOR NATIVE
export const UPLOAD_IMAGE_REQUEST = 'UPLOAD_IMAGE_REQUEST';
export const UPLOAD_IMAGE_SUCCESS = 'UPLOAD_IMAGE_SUCCESS';
export const UPLOAD_IMAGE_FAILURE = 'UPLOAD_IMAGE_FAILURE';

//GET COUNTRIES
export const GET_COUNTRIES_START = 'GET_COUNTRIES_START';
export const GET_COUNTRIES_REQUEST = 'GET_COUNTRIES_REQUEST';
export const GET_COUNTRIES_SUCCESS = 'GET_COUNTRIES_SUCCESS';
export const GET_COUNTRIES_FAILURE = 'GET_COUNTRIES_FAILURE';

//GET CITIES
export const GET_CITIES_START = 'GET_CITIES_START';
export const GET_CITIES_REQUEST = 'GET_CITIES_REQUEST';
export const GET_CITIES_SUCCESS = 'GET_CITIES_SUCCESS';
export const GET_CITIES_FAILURE = 'GET_CITIES_FAILURE';

//GET CURRENCIES
export const GET_CURRENCIES_START = 'GET_CURRENCIES_START';
export const GET_CURRENCIES_REQUEST = 'GET_CURRENCIES_REQUEST';
export const GET_CURRENCIES_SUCCESS = 'GET_CURRENCIES_SUCCESS';
export const GET_CURRENCIES_FAILURE = 'GET_CURRENCIES_FAILURE';

//UPDATE FORM FIELDS
export const UPDATE_FORM = 'UPDATE_FORM';
export const UPDATE_ONBOARDING_FORM = 'UPDATE_ONBOARDING_FORM';

//EXPLORE
export const GET_EXPLORE_DATA_START = 'GET_EXPLORE_DATA_START';
export const GET_EXPLORE_DATA_REQUEST = 'GET_EXPLORE_DATA_REQUEST';
export const GET_EXPLORE_DATA_SUCCESS = 'GET_EXPLORE_DATA_SUCCESS';
export const GET_EXPLORE_DATA_FAILURE = 'GET_EXPLORE_DATA_FAILURE';

export const SET_EXPLORE_DATA_START = 'SET_EXPLORE_DATA_START';
export const SET_EXPLORE_DATA_REQUEST = 'SET_EXPLORE_DATA_REQUEST';
export const SET_EXPLORE_DATA_SUCCESS = 'SET_EXPLORE_DATA_SUCCESS';
export const SET_EXPLORE_DATA_FAILURE = 'SET_EXPLORE_DATA_FAILURE';

export const SEARCH_PROFILES_START = 'SEARCH_PROFILES_START';
export const SEARCH_PROFILES_REQUEST = 'SEARCH_PROFILES_REQUEST';
export const SEARCH_PROFILES_SUCCESS = 'SEARCH_PROFILES_SUCCESS';
export const SEARCH_PROFILES_FAILURE = 'SEARCH_PROFILES_FAILURE';

export const SET_EXPLORE_VIEWED = 'SET_EXPLORE_VIEWED';
export const SET_EXPLORE_UNVIEWED = 'SET_EXPLORE_UNVIEWED';

//CONNECTION
export const GET_CONNECTION_START = 'GET_CONNECTION_START';
export const GET_CONNECTION_REQUEST = 'GET_CONNECTION_REQUEST';
export const GET_CONNECTION_SUCCESS = 'GET_CONNECTION_SUCCESS';
export const GET_CONNECTION_FAILURE = 'GET_CONNECTION_FAILURE';

// GET TWILIO ACCESS TOKEN
export const GET_CHAT_ACCESS_TOKEN_START = 'GET_CHAT_ACCESS_TOKEN_START';
export const GET_CHAT_ACCESS_TOKEN_REQUEST = 'GET_CHAT_ACCESS_TOKEN_REQUEST';
export const GET_CHAT_ACCESS_TOKEN_SUCCESS = 'GET_CHAT_ACCESS_TOKEN_SUCCESS';
export const GET_CHAT_ACCESS_TOKEN_FAILURE = 'GET_CHAT_ACCESS_TOKEN_FAILURE';

export const GET_UNREAD_MESSAGE_START = 'GET_UNREAD_MESSAGE_START';
export const GET_UNREAD_MESSAGE_REQUEST = 'GET_UNREAD_MESSAGE_REQUEST';
export const GET_UNREAD_MESSAGE_SUCCESS = 'GET_UNREAD_MESSAGE_SUCCESS';
export const GET_UNREAD_MESSAGE_FAILURE = 'GET_UNREAD_MESSAGE_FAILURE';

export const GET_CHAT_HISTORY_START = 'GET_CHAT_HISTORY_START';
export const GET_CHAT_HISTORY_REQUEST = 'GET_CHAT_HISTORY_REQUEST';
export const GET_CHAT_HISTORY_SUCCESS = 'GET_CHAT_HISTORY_SUCCESS';
export const GET_CHAT_HISTORY_FAILURE = 'GET_CHAT_HISTORY_FAILURE';

export const UPDATE_CHANNEL_INFO_START = 'UPDATE_CHANNEL_INFO_START';
export const UPDATE_CHANNEL_INFO_SUCCESS = 'UPDATE_CHANNEL_INFO_SUCCESS';

export const SEND_PUSH_NOTIFICATION_START = 'SEND_PUSH_NOTIFICATION_START';
export const SEND_PUSH_NOTIFICATION_REQUEST = 'SEND_PUSH_NOTIFICATION_REQUEST';
export const SEND_PUSH_NOTIFICATION_SUCCESS = 'SEND_PUSH_NOTIFICATION_SUCCESS';
export const SEND_PUSH_NOTIFICATION_FAILURE = 'SEND_PUSH_NOTIFICATION_FAILURE';

//GET PROFILES
export const GET_PROFILE_INFO_START = 'GET_PROFILE_INFO_START';
export const GET_PROFILE_INFO_REQUEST = 'GET_PROFILE_INFO_REQUEST';
export const GET_PROFILE_INFO_SUCCESS = 'GET_PROFILE_INFO_SUCCESS';
export const GET_PROFILE_INFO_FAILURE = 'GET_PROFILE_INFO_FAILURE';

//ADD FCM TOKEN
export const ADD_FCM_TOKEN_START = 'ADD_FCM_TOKEN_START'; //NATIVE SPECIFIC CODE
export const ADD_FCM_TOKEN_REQUEST = 'ADD_FCM_TOKEN_REQUEST'; //NATIVE SPECIFIC CODE
export const ADD_FCM_TOKEN_SUCCESS = 'ADD_FCM_TOKEN_SUCCESS'; //NATIVE SPECIFIC CODE
export const ADD_FCM_TOKEN_FAILURE = 'ADD_FCM_TOKEN_FAILURE'; //NATIVE SPECIFIC CODE

//DELETE FCM TOKEN
export const DELETE_FCM_TOKEN_START = 'DELETE_FCM_TOKEN_START'; //NATIVE SPECIFIC CODE
export const DELETE_FCM_TOKEN_REQUEST = 'DELETE_FCM_TOKEN_REQUEST'; //NATIVE SPECIFIC CODE
export const DELETE_FCM_TOKEN_SUCCESS = 'DELETE_FCM_TOKEN_SUCCESS'; //NATIVE SPECIFIC CODE
export const DELETE_FCM_TOKEN_FAILURE = 'DELETE_FCM_TOKEN_FAILURE'; //NATIVE SPECIFIC CODE

//RESET
export const LOGOUT = 'LOGOUT';
export const RESET_AUTH = 'RESET_AUTH';
export const RESET_FORM = 'RESET_FORM';
export const RESET_MISC = 'RESET_MISC';
export const RESET_PROFILE = 'RESET_PROFILE';
export const RESET_JOB = 'RESET_JOB';
export const RESET_UPLOAD = 'RESET_UPLOAD';
export const RESET_EXPLORE = 'RESET_EXPLORE';
export const RESET_CONNECTION = 'RESET_CONNECTION';
export const RESET_CHAT = 'RESET_CHAT';
export const RESET_PROFILE_INFO = 'RESET_PROFILE_INFO';
export const RESET_FCM_TOKEN = 'RESET_FCM_TOKEN'; //NATIVE SPECIFIC CODE

//TEST
export const TEST_ADD = 'TEST_ADD';
export const TEST_ADD_PLUS = 'TEST_ADD_PLUS';
